### ISSUE TITLE
 Incorrect time zone in the monthly report

### ISSUE THREAD

**Issue by oliveiragabriel07** [fmilani/contatempo#1]
The time entries in the monthly report are being displayed in a timezone different from the app.

**Comment by fmilani** [comment]
Hi Gabriel.

First of all, thanks for reporting the issue.

The problem was that the server runs in a different timezone from the users. Because the server is responsible for formatting the dates sent in the monthly reports, it was using its own timezone to format them.

I'm adding a new setting where the user can choose his timezone and the server will user this setting to format the dates. Hang on, this will soon be fixed

**Comment by fmilani** [comment]
#3 seems to have resolved this, so I'm closing the issue.

Anyone, feel free to reopen if this is still an issue
